[phases.setup]
nixPkgs = [
  "nodejs",
  "npm",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "ttf-dejavu",
  "libxkbcommon"
]

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[start]
cmd = "node index.js"

